[package]
name = "serde-versions-derive"
version = "0.0.1"
authors = ["Willem Olding <willemolding@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"

[dev-dependencies]
serde = { version = "1.0.126", features = ['derive'] }
serde_json = "1.0.64"
